### ISSUE TITLE
docker-compose.yml doesn't take KARAPACE_SECURITY_PROTOCOL and KARAPACE_SASL_MECHANISM as environment variables.

### ISSUE THREAD

**Issue by YuWang24** [aiven/karapace#259]
# What happened?
I ran karapace in a docker container, tried to connect to my Kafka cluster that uses a **SASL_PLAINTEXT** as **security_protocol** and **SCRAM-SHA-256** as **sasl_mechanism**. 

I used a docker-compose.yml as below:
```
version: '3'
services:
  karapace-registry:
    image: aivenoy/karapace:latest
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - registry
    ports:
      - "8081:8081"
    environment:
      KARAPACE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KARAPACE_SASL_MECHANISM: SCRAM-SHA-256
      KARAPACE_SASL_PLAIN_USERNAME: "<my_username>"
      KARAPACE_SASL_PLAIN_PASSWORD: "<my_password>"
      KARAPACE_REGISTRY_ADVERTISED_HOSTNAME: karapace-registry
      KARAPACE_REGISTRY_BOOTSTRAP_URI: <kafka-node-ip>:9092
      KARAPACE_REGISTRY_PORT: 8081
      KARAPACE_REGISTRY_HOST: 0.0.0.0
      KARAPACE_REGISTRY_CLIENT_ID: karapace
      KARAPACE_REGISTRY_GROUP_ID: karapace-registry
      KARAPACE_REGISTRY_MASTER_ELIGIBITY: "true"
      KARAPACE_REGISTRY_TOPIC_NAME: _schemas
      KARAPACE_REGISTRY_LOG_LEVEL: WARNING

  karapace-rest:
    image: aivenoy/karapace:latest
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - rest
    depends_on:
      - karapace-registry
    ports:
      - "8082:8082"
    environment:
      KARAPACE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KARAPACE_SASL_MECHANISM: SCRAM-SHA-256
      KARAPACE_SASL_PLAIN_USERNAME: "<my_username>"
      KARAPACE_SASL_PLAIN_PASSWORD: "<my_password>"
      KARAPACE_REST_PORT: 8082
      KARAPACE_REST_HOST: 0.0.0.0
      KARAPACE_REST_ADVERTISED_HOSTNAME: karapace-rest
      KARAPACE_REST_BOOTSTRAP_URI: <kafka-node-ip>:9092
      KARAPACE_REST_REGISTRY_HOST: karapace-registry
      KARAPACE_REST_REGISTRY_PORT: 8081
      # Keep in sync with tests/integration/conftest.py::fixture_rest_async,
      # new entries may need to be added to containers/start.sh
      KARAPACE_REST_ADMIN_METADATA_MAX_AGE: 0
      KARAPACE_REST_LOG_LEVEL: WARNING
```

I got the following error:
`AssertionError: sasl_mechanism must be in PLAIN, GSSAPI, OAUTHBEARER, SCRAM-SHA-256, SCRAM-SHA-512`

I had a look at the **start.sh**, I found that **security_protocol** is hard coded as `"security_protocol": "PLAINTEXT"`. And there are no configs for **sasl_mechanism**, **sasl_plain_username**, and **sasl_plain_password**.

# What did you expect to happen?
I expect the karapace container to be able to connect to my Kafka cluster that uses the SASL_PLAINTEXT and SCRAM-SHA-256. Could anyone be able to solve this issue by fixing this? Thanks in advance. 

# What else do we need to know?

Include your platform, version, and any other information that seems relevant.
