### ISSUE TITLE
 Protobuf Schema Lookups Via subject/<subject> Failing (also protobuf creation is not idempotent)

### ISSUE THREAD

**Issue by strokyl** [aiven/karapace#442]
# What happened?

From version `3.1.0` to version `3.3.1` (the latest version at this ticket edition moment). The `subjects/<subject>` POST endpoint no longer returns the version of a known protobuf schema, instead, it throws a `40403` (Schema not found) error.
I also noticed while looking for this bug that POST `subjects/<subject>/versions` called twice with the same protobuf schema will create to version instead of just one.
This bug make `io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer` fails.

# What did you expect to happen?

I think that when trying to create a new version with the same protobuf schema than the previous one we should not create a new version and just return the already existing id for this schema.
I also think user should be able to get the id of an existing protobuf version.

# What else do we need to know?

This issue is really similar to https://github.com/aiven/karapace/issues/428: (also maybe you should check the idempotent issue with JSON schema)
Here the script I used:
```bash
#!/bin/bash


protobuf_schema='syntax = \"proto3\";\n\nmessage Record {\nint32 id = 1;\nstring createdAt = 2;\nstring name = 3;\n}'

create_schema() {
	curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
		--data '{"schemaType": "PROTOBUF", "schema": "'"$protobuf_schema"'"}' \
		http://localhost:8081/subjects/protobuf_test/versions
}

retrieving_schema_id () {
	curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
		--data '{"schemaType": "PROTOBUF", "schema": "'"$protobuf_schema"'"}' \
		http://localhost:8081/subjects/protobuf_test/
	}

perform_test () {
	echo "Creating protobuf schema"
	create_schema 
	echo
	echo "Creating again same schema"
	create_schema 
	echo
	echo "retrieving back schema id"
	retrieving_schema_id
	echo
}

start_karapace() {
	VERSION=$1 docker-compose up -d >/dev/null 2>&1
	sleep 3 #wait karapace is really started
}

for version in 2.1.3 3.0.0 3.1.0 3.1.1 3.1.2 3.2.0 3.3.0 3.3.1
do
	echo "[START]"
	echo "Running test for version: $version"
	start_karapace "$version"
	perform_test
	echo "[STOP]"
	echo
	echo
done
```

The docker-compose file:
```yaml
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9101:9101"  # JMX
      - "9092:9092"  # Kafka
    environment:
      # Listeners:
      # PLAINTEXT_HOST -> Expose kafka to the host network
      # PLAINTEXT -> Used by kafka for inter broker communication / containers
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://karapace-registry:8081
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      # Metrics:
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      # Keep in sync with tests/integration/conftest.py::configure_and_start_kafka
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "local"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_INTER_BROKER_PROTOCOL_VERSION: 2.4
      KAFKA_LOG_CLEANER_ENABLE: "true"
      KAFKA_LOG_MESSAGE_FORMAT_VERSION: 2.4
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_SEGMENT_BYTES: 209715200
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_NUM_NETWORK_THREADS: 112
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_NUM_REPLICA_FETCHERS: 4
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS: 16
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  karapace-registry:
    image: ghcr.io/aiven/karapace:$VERSION
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      KARAPACE_ADVERTISED_HOSTNAME: karapace-registry
      KARAPACE_BOOTSTRAP_URI: kafka:29092
      KARAPACE_PORT: 8081
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_CLIENT_ID: karapace
      KARAPACE_GROUP_ID: karapace-registry
      KARAPACE_MASTER_ELIGIBILITY: "true"
      KARAPACE_TOPIC_NAME: _schemas
      KARAPACE_LOG_LEVEL: WARNING
      KARAPACE_COMPATIBILITY: FULL
```

and here the console output:
```
[START]
Running test for version: 2.1.3
Creating protobuf schema
{"id":1}
Creating again same schema
{"id":1}
retrieving back schema id
{"id":1,"schema":"syntax = \"proto3\";\n\nmessage Record {\nint32 id = 1;\nstring createdAt = 2;\nstring name = 3;\n}","schemaType":"PROTOBUF","subject":"protobuf_test","version":1}
[STOP]


[START]
Running test for version: 3.0.0
Creating protobuf schema
{"id":1}
Creating again same schema
{"id":1}
retrieving back schema id
{"id":1,"schema":"syntax = \"proto3\";\n\nmessage Record {\nint32 id = 1;\nstring createdAt = 2;\nstring name = 3;\n}","schemaType":"PROTOBUF","subject":"protobuf_test","version":1}
[STOP]


[START]
Running test for version: 3.1.0
Creating protobuf schema
{"id":2}
Creating again same schema
{"id":3}
retrieving back schema id
{"error_code":40403,"message":"Schema not found"}
[STOP]


[START]
Running test for version: 3.1.1
Creating protobuf schema
{"id":4}
Creating again same schema
{"id":5}
retrieving back schema id
{"error_code":40403,"message":"Schema not found"}
[STOP]


[START]
Running test for version: 3.1.2
Creating protobuf schema
{"id": 6}
Creating again same schema
{"id": 7}
retrieving back schema id
{"error_code": 40403, "message": "Schema not found"}
[STOP]


[START]
Running test for version: 3.2.0
Creating protobuf schema
{"id": 8}
Creating again same schema
{"id": 9}
retrieving back schema id
{"error_code": 40403, "message": "Schema not found"}
[STOP]


[START]
Running test for version: 3.3.0
Creating protobuf schema
{"id": 10}
Creating again same schema
{"id": 11}
retrieving back schema id
{"error_code": 40403, "message": "Schema not found"}
[STOP]


[START]
Running test for version: 3.3.1
Creating protobuf schema
{"id": 12}
Creating again same schema
{"id": 13}
retrieving back schema id
{"error_code": 40403, "message": "Schema not found"}
[STOP]
```
